apiVersion: v1
kind: Pod
metadata:
  name: teamcity-build-agent
spec:
  containers:
  - name: teamcity-build-agent
    image: tolache/teamcity-agent:latest
    imagePullPolicy: Always
    env:
    - name: DOCKER_IN_DOCKER
      value: start
    # !! TEST LAB ONLY !! Privileged root can escape to the host. Needed for DinD.
    securityContext:
      privileged: true
      runAsUser: 0
    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "2Gi"
