apiVersion: v1
kind: PodTemplate
metadata:
  name: tolache-custom
  namespace: teamcity-executor
template:
  spec:
    containers:
    - name: template-container # see the limitations section
      image: tolache/teamcity-agent:latest
      resources:
        limits:
          ephemeral-storage: 10Gi
          memory: 2Gi
        requests:
          ephemeral-storage: 5Gi
    nodeSelector:
      kubernetes.io/os: linux
