services:

  sonarqube:
    image: sonarqube:${SONARQUBE_VERSION}
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
      SONAR_WEB_JAVAOPTS: "-Xms256m -Xmx512m"
      SONAR_CE_JAVAOPTS: "-Xms256m -Xmx512m"
      SONAR_SEARCH_JAVAOPTS: "-Xms512m -Xmx512m"
    ports:
      - "9002:9000"
    volumes:
      - ./sonarqube/conf:/opt/sonarqube/conf
      - ./sonarqube/data:/opt/sonarqube/data
      - ./sonarqube/extensions:/opt/sonarqube/extensions
      - ./sonarqube/logs:/opt/sonarqube/logs
      - ./sonarqube/temp:/opt/sonarqube/temp
    networks:
      default:
        priority: 100
      kind:
        priority: 0
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G

  sonarqube-db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./sonarqube-db:/var/lib/postgresql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 64M
